'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage_Product_Info
    
    '''<summary>
    '''pnlList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTotalList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ColEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColEdit As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ColDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColDelete As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''rptList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblEditMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditMode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdIsSerial_Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdIsSerial_Yes As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdIsSerial_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdIsSerial_No As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''ddlBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBrand As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rdRequireReceive_Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdRequireReceive_Yes As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdRequireReceive_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdRequireReceive_No As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Tab_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_THAI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Tab_ENGLISH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_ENGLISH As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Tab_CHINESE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_CHINESE As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Tab_JAPANESE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_JAPANESE As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Tab_KOREAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_KOREAN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Tab_RUSSIAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab_RUSSIAN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtDisplayName_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_TH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_TH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_TH As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_TH As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_TH As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_TH As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_TH As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_TH As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtDisplayName_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_EN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_EN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_EN As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_EN As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_EN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_EN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_EN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_EN As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtDisplayName_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_CN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_CN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_CN As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_CN As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_CN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_CN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_CN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_CN As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtDisplayName_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_JP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_JP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_JP As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_JP As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_JP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_JP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_JP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_JP As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtDisplayName_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_KR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_KR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_KR As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_KR As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_KR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_KR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_KR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_KR As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtDisplayName_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisplayName_RS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_RS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgIcon_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon_RS As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ful_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ful_RS As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpdateLogo_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateLogo_RS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCapion_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCapion_RS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddSpec_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSpec_RS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptCaptionList_RS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCaptionList_RS As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.LinkButton
End Class
