'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage
    
    '''<summary>
    '''HeaderContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderContainer As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''mnu_Dashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Dashboard As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''badge_Dashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents badge_Dashboard As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Dashboard_Overall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Dashboard_Overall As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''badge_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents badge_Report As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Product_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Product_Input As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Product_Output control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Product_Output As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Product_Stock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Product_Stock As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Product_Warning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Product_Warning As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_TMS_EDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_TMS_EDI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Money_Stock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Money_Stock As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Money_Transaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Money_Transaction As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Sale_Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Sale_Summary As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Hot_Sale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Hot_Sale As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Report_Customer_Transaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Report_Customer_Transaction As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Management control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Management As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''badge_Management control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents badge_Management As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Manage_Machine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Manage_Machine As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Manage_Product_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Manage_Product_Input As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Manage_Shift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Manage_Shift As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Manage_Product_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Manage_Product_Info As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Manage_Brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Manage_Brand As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Setting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''badge_Setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents badge_Setting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Setting_Site control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Setting_Site As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mnu_Setting_Authorize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnu_Setting_Authorize As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''scm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scm As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''ScriptContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptContainer As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
