'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Kiosk_Shelf
    
    '''<summary>
    '''Shelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Shelf As Global.VDM.UC_Product_Shelf
    
    '''<summary>
    '''pnlShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShelf As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtShelfWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShelfWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShelfHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShelfHeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShelfDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShelfDepth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnClearShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearShelf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnApplyShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyShelf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseShelf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFloor As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFloorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFloorName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFloorWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFloorWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFloorHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFloorHeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFloorDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFloorDepth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFloorY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFloorY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnRemoveFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveFloor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnApplyFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyFloor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseFloor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlot As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSlotName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlotName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSlotWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlotWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSlotHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlotHeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSlotDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlotDepth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSlotX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlotX As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSlotY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSlotY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_ProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_ProductCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlotQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlotQuantity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSlotCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlotCapacity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''levelProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents levelProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFreeSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreeSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMaxSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tagSlot_Empty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tagSlot_Empty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnRemoveSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveSlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnMoveToSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveToSlot As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnApplySlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplySlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCloseSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseSlot As Global.System.Web.UI.WebControls.LinkButton
End Class
