'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Printer_Stock_UI
    
    '''<summary>
    '''pnlPrinterStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrinterStock As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPrintPaper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintPaper As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlPrinterProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrinterProgress As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''barPrinterLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents barPrinterLevel As Global.System.Web.UI.WebControls.Panel
End Class
