'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Test_API_Interface
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''pnl_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_btn As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnFace_Recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFace_Recognition As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Prepaid_Validate_Register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Prepaid_Validate_Register As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Generate_Order_Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Generate_Order_Id As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Delete_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Delete_File As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Save_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save_File As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_Flow_Create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_Flow_Create As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_Flow_Finish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_Flow_Finish As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Activity_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Activity_Start As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Activity_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Activity_End As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Get_Product_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Get_Product_Info As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_GenerateOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_GenerateOrderID As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_SaveOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_SaveOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_SubmitOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_SubmitOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_Service_GetOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Service_GetOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnl_face_recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_face_recognition As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Face_Recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Face_Recognition As Global.VDM.UC_Face_Recognition
    
    '''<summary>
    '''pnl_Prepaid_Validate_Register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Prepaid_Validate_Register As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Prepaid_Validate_Register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Prepaid_Validate_Register As Global.VDM.UC_Prepaid_Validate_Register
    
    '''<summary>
    '''pnl_Generate_Order_Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Generate_Order_Id As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Generate_Order_Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Generate_Order_Id As Global.VDM.UC_Generate_Order_Id
    
    '''<summary>
    '''pnl_Delete_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Delete_File As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Delete_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Delete_File As Global.VDM.UC_Delete_File
    
    '''<summary>
    '''pnl_Save_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Save_File As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Save_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Save_File As Global.VDM.UC_Save_File
    
    '''<summary>
    '''pnl_Service_Flow_Create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Service_Flow_Create As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Service_Flow_Create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Service_Flow_Create As Global.VDM.UC_Service_Flow_Create
    
    '''<summary>
    '''pnl_Service_Flow_Finish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Service_Flow_Finish As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Service_Flow_Finish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Service_Flow_Finish As Global.VDM.UC_Service_Flow_Finish
    
    '''<summary>
    '''pnl_Activity_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Activity_Start As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Activity_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Activity_Start As Global.VDM.UC_Activity_Start
    
    '''<summary>
    '''pnl_Activity_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Activity_End As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Activity_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Activity_End As Global.VDM.UC_Activity_End
    
    '''<summary>
    '''pnl_Get_Product_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Get_Product_Info As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Get_Product_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Get_Product_Info As Global.VDM.UC_Get_Product_Info
    
    '''<summary>
    '''pnl_Service_GenerateOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Service_GenerateOrderID As Global.System.Web.UI.WebControls.Panel

End Class
