'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Auto_Prepaid_Register
    
    '''<summary>
    '''Face_cust_certificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Face_cust_certificate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Face_cust_capture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Face_cust_capture As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SIM_Serial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIM_Serial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''KO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KO_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''USER_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents USER_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXN_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXN_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_TITLE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_NAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_SURNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_SURNAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NAT_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAT_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_GENDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_GENDER As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_BIRTHDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_BIRTHDATE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_START control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_START As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_EXPIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_EXPIRE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Request As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReturnResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturnResult As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblErr_Msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErr_Msg As Global.System.Web.UI.WebControls.Label
End Class
