'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Delete_File
    
    '''<summary>
    '''order_id_REQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents order_id_REQ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''form_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form_type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Request As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trx_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trx_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''process_instance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents process_instance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ref_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ref_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''order_id_RESP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents order_id_RESP As Global.System.Web.UI.WebControls.TextBox
End Class
