'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Get_Product_Info
    
    '''<summary>
    '''productCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents productCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Request As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DESCRIPTION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PLANT_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLANT_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PRODUCT_BRAND_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRODUCT_BRAND_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PRODUCT_MODEL_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRODUCT_MODEL_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IS_SERIAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IS_SERIAL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PRODUCT_TYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRODUCT_TYPE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DISPLAY_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DISPLAY_NAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IS_ENABLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IS_ENABLE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IS_DELETE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IS_DELETE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CATEGORY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CATEGORY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''REQ_SALE_APPROACH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REQ_SALE_APPROACH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IS_VAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IS_VAT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''VAT_RATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VAT_RATE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''COMPANY_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPANY_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IS_SIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IS_SIM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''REQUIRE_RECEIVE_FORM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REQUIRE_RECEIVE_FORM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''APPLE_CARE_SERVICE_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents APPLE_CARE_SERVICE_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''COLOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COLOR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CAPACITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAPACITY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CATEGORY_RECOMMEND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CATEGORY_RECOMMEND As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Price As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SEQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SEQ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PRODUCT_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRODUCT_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CAPTION_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAPTION_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CAPTION_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAPTION_DESC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DETAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DETAIL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblErr_Msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErr_Msg As Global.System.Web.UI.WebControls.Label
End Class
