'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Prepaid_Validate_Register
    
    '''<summary>
    '''key_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents key_type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''key_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents key_value As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Request As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trx_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trx_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''process_instance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents process_instance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''subscriber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subscriber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sim As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imsi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sim_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sim_category As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''priceplan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents priceplan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''company_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''is_registered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents is_registered As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastname As Global.System.Web.UI.WebControls.TextBox
End Class
