'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Prepaid_Register
    
    '''<summary>
    '''OrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_gender As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''customer_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_title As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_language control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_language As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_title_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_title_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_firstname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_lastname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_birthdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_birthdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''doc_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doc_type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_id_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_id_number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''customer_id_expire_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customer_id_expire_date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_moo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_moo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_village control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_village As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_street As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_soi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_district control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_district As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_province As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_building_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_building_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_building_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_building_room As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_building_floor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_building_floor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sddress_sub_district control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sddress_sub_district As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''address_zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address_zip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''shopCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shopCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''shopName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shopName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sale_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sale_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mat_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mat_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mat_desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mat_desc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sim_serial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sim_serial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''require_print_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents require_print_form As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''price_plan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents price_plan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''subscriber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subscriber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''is_registered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents is_registered As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sub_activity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sub_activity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''company_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Request As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trx_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trx_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''process_instance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents process_instance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''response_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents response_data As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''message_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents message_code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''message_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents message_type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''en_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents en_message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''th_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''technical_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents technical_message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''messagefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messagefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''detailed_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailed_message As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblErr_Msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErr_Msg As Global.System.Web.UI.WebControls.Label
End Class
