'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestScan
    
    '''<summary>
    '''UDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDP As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlScanProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScanProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnZoomOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnZoomOut As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnZoomReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnZoomReset As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnZoomIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnZoomIn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Shelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Shelf As Global.VDM.UC_Product_Shelf
    
    '''<summary>
    '''pnlSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlot As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSlotName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlotName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSeeShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSeeShelf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgSlot_Product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSlot_Product As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblSlot_ProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_ProductCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_ProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_ProductName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_ProductDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_ProductDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tagSlot_Empty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tagSlot_Empty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgSlot_Brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSlot_Brand As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''pnlSlotProductSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlotProductSize As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSlot_Product_Width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Product_Width As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_Product_Height control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Product_Height As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_Product_Depth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Product_Depth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_Width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Width As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_Height control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Height As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_Depth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_Depth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSlotCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlotCapacity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''levelProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents levelProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFreeSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreeSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMaxSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptSlotProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSlotProduct As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnMoveRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveRight As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblTotalScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBarcode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptProductTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProductTab As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScan As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgScan_Product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgScan_Product As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblScan_ProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_ProductCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScan_ProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_ProductName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScan_ProductDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_ProductDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgScan_Brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgScan_Brand As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblScan_Product_Width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_Product_Width As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScan_Product_Height control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_Product_Height As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScan_Product_Depth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_Product_Depth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkScan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptScan As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnMoveLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveLeft As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button
End Class
