'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Product_Floor
    
    '''<summary>
    '''Floor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Floor As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CaptionBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaptionBlock As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''FloorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMenu As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mnuFloorSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuFloorSetting As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mnuAddFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAddFloor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mnuAddSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuAddSlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mnuClearAllSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuClearAllSlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mnuClearAllProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuClearAllProduct As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mnuRemoveFloor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuRemoveFloor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSlot As Global.System.Web.UI.WebControls.Repeater
End Class
