'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SIM_Stock
    
    '''<summary>
    '''Dispenser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dispenser As Global.VDM.UC_SIM_Dispenser
    
    '''<summary>
    '''pnlSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlot As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSlotID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlotID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSeeShelf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSeeShelf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSlot As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblSlot_SIMCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_SIMCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlotQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlotQuantity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSlot_SIMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlot_SIMName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tagSlot_Empty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tagSlot_Empty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlSlotCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSlotCapacity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''levelSIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents levelSIM As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFreeSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreeSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMaxSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxSpace As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSlot As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSlot As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnMoveRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveRight As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBarcode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTotalScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBarcode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptProductTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProductTab As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScan As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgScan As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblScan_SIMCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_SIMCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblScan_SIMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScan_SIMName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkScan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''rptScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptScan As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnMoveLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveLeft As Global.System.Web.UI.WebControls.LinkButton
End Class
