'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Shift_Change
    
    '''<summary>
    '''txt_coin1_Before control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin1_Before As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_coin1_Pick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin1_Pick As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_coin1_Pick_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_coin1_Pick_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_coin1_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin1_Input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_coin1_Input_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_coin1_Input_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_coin1_Remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin1_Remain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_coin1_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_coin1_Amount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_coin5_Before control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin5_Before As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_coin5_Pick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin5_Pick As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_coin5_Pick_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_coin5_Pick_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_coin5_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin5_Input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_coin5_Input_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_coin5_Input_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_coin5_Remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_coin5_Remain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_coin5_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_coin5_Amount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cash20_Before control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash20_Before As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_cash20_Pick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash20_Pick As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_cash20_Pick_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cash20_Pick_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_cash20_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash20_Input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_cash20_Input_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cash20_Input_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_cash20_Remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash20_Remain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_cash20_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cash20_Amount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cash100_Before control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash100_Before As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_cash100_Pick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash100_Pick As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_cash100_Pick_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cash100_Pick_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_cash100_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash100_Input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_cash100_Input_Full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cash100_Input_Full As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_cash100_Remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cash100_Remain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_cash100_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cash100_Amount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSum As Global.System.Web.UI.WebControls.Label
End Class
