'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Device_Verify
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''formStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formStep As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPrice_str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrice_str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrice_Money control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrice_Money As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrency_Str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrency_Str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlScanIDCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScanIDCard As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Scan_IDCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Scan_IDCart As Global.VDM.UC_Scan_IDCart
    
    '''<summary>
    '''pnlFace_Recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFace_Recognition As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UC_Scan_Face_Recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Scan_Face_Recognition As Global.VDM.UC_Scan_Face_Recognition
    
    '''<summary>
    '''btnSkip_ScanIDCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSkip_ScanIDCard As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlModul_IDCard_Success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModul_IDCard_Success As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnStart_Take_Photos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStart_Take_Photos As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHome As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lnkBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''id_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Face_cust_certificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Face_cust_certificate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Face_cust_capture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Face_cust_capture As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_TITLE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_NAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_SURNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_SURNAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NAT_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAT_CODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_GENDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_GENDER As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_BIRTHDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_BIRTHDATE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_START control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_START As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_PASSPORT_EXPIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_PASSPORT_EXPIRE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CUS_IMAGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CUS_IMAGE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFace_Recognition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFace_Recognition As Global.System.Web.UI.WebControls.Button
End Class
