'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Device_Payment
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''udpList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udpList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtLocalControllerURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocalControllerURL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblDISPLAY_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDISPLAY_NAME As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCapacity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCapacity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''formStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formStep As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPrice_str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrice_str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCurrency_Str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrency_Str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkCash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCash As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lnkCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCredit As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lnkTruemoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTruemoney As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''pnlSelectChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectChoice As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlCash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCash As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRequire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequire As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt50 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt100 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt500 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt1000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt1000 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCashProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCashProblem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnCashCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCashCompleted As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCashTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCashTimeout As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCashProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCashProblem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlTruemoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTruemoney As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBarcode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBarcode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSkip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSkip As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHome As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lnkBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''pnlCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCredit As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''paymentGatewayWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymentGatewayWindow As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''txtCreditReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreditReq As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnCreditComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreditComplete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkCloseCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCloseCredit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''CommonUI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommonUI As Global.VDM.UC_CommonUI
    
    '''<summary>
    '''UC_CommonUI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_CommonUI As Global.VDM.UC_CommonUI
End Class
