'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Device_Shoping_Cart
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''SCM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SCM As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblDISPLAY_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDISPLAY_NAME As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCapacity As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCapacity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrice_str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrice_str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrice_Money control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrice_Money As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrency_Str control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrency_Str As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UDPTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDPTerm As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerify As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnVerifySlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerifySlip As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lnkHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHome As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lnkBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtLocalControllerURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocalControllerURL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UC_CommonUI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_CommonUI As Global.VDM.UC_CommonUI
    
    '''<summary>
    '''UDBVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDBVerify As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''id_Citizenid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Citizenid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Th_Prefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Th_Prefix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Th_Firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Th_Firstname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Th_Middlename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Th_Middlename As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Th_Lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Th_Lastname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_En_Prefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_En_Prefix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_En_Firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_En_Firstname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_En_Middlename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_En_Middlename As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_En_Lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_En_Lastname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Sex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Sex As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Birthday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Birthday As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Address As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrHouseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrHouseNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrVillageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrVillageNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrLane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrLane As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrRoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrRoad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrTambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrTambol As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrAmphur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrAmphur As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_addrProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_addrProvince As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Issue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Issue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Issuer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Issuer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Expire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Expire As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''id_Photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_Photo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_FirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_FirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_MiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_MiddleName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_LastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_LastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_DocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_DocType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_Nationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_Nationality As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_PassportNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_PassportNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_DateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_DateOfBirth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_Sex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_Sex As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_Expire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_Expire As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_PersonalID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_PersonalID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_IssueCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_IssueCountry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_MRZ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_MRZ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pass_Photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pass_Photo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnKeepInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKeepInfo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''clickIDCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickIDCard As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''clickIDCardAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickIDCardAlert As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''clickIDCardCross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickIDCardCross As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''clickPassportAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickPassportAlert As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''clickPassportCross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickPassportCross As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnNextSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextSlip As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lnkSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSlip As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''clickCamTrigger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickCamTrigger As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''txtCamData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCamData As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnPostCam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPostCam As Global.System.Web.UI.WebControls.Button
End Class
