'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Select_Language
    
    '''<summary>
    '''TH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TH As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''EN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EN As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''CN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CN As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''JP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JP As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''KR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KR As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''RU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RU As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
