'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Dialog
    
    '''<summary>
    '''pnlModul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModul As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbl_HeaderMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_HeaderMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAlert As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lbl_DetailMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DetailMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnClose_Dialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose_Dialog As Global.System.Web.UI.WebControls.LinkButton
End Class
